// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Shape from "./Shape.res.mjs";
import * as Codegen from "./Codegen.res.mjs";

function log(prim) {
  console.log(prim);
}

function printShape(name, shape) {
  let strs = shape.map(d => d.toString());
  let joined = strs.join(", ");
  console.log(name + ": [" + joined + "]");
}

function testInfer(name, op, inputs) {
  let s = Shape.infer(op, inputs);
  if (s !== undefined) {
    return printShape(name, s);
  } else {
    console.log(name + ": None");
    return;
  }
}

function testCodegen(name, op, inputs) {
  let match = Codegen.generate(op, inputs);
  if (match !== undefined) {
    let match$1 = match[1].workgroupCount;
    let prim = name + ": " + match[0].name + " (" + match$1[0].toString() + "x" + match$1[1].toString() + ")";
    console.log(prim);
    return;
  }
  console.log(name + ": FAILED");
}

console.log("=== Shape Inference ===");

testInfer("Input", {
  TAG: "Input",
  shape: [
    32,
    224,
    224,
    3
  ],
  dtype: "F32"
}, []);

testInfer("Add broadcast", "Add", [
  [
    32,
    1,
    64
  ],
  [
    1,
    10,
    64
  ]
]);

testInfer("MatMul", "MatMul", [
  [
    32,
    128,
    64
  ],
  [
    32,
    64,
    256
  ]
]);

console.log("\n=== Codegen ===");

testCodegen("ReLU", "ReLU", [[
    4,
    256
  ]]);

testCodegen("Add", "Add", [
  [
    4,
    256
  ],
  [
    4,
    256
  ]
]);

testCodegen("MatMul", "MatMul", [
  [
    64,
    128
  ],
  [
    128,
    64
  ]
]);

testCodegen("Reduce Sum", {
  TAG: "Reduce",
  op: "Sum",
  axes: [-1],
  keepDims: false
}, [[
    32,
    128
  ]]);

testCodegen("Reduce Mean", {
  TAG: "Reduce",
  op: "Mean",
  axes: [
    1,
    2
  ],
  keepDims: false
}, [[
    8,
    32,
    32,
    3
  ]]);

testCodegen("Softmax", {
  TAG: "Softmax",
  axis: -1
}, [[
    4,
    1000
  ]]);

testCodegen("Dense", {
  TAG: "Dense",
  units: 256,
  useBias: true
}, [[
    8,
    512
  ]]);

testCodegen("MaxPool2D", {
  TAG: "MaxPool2D",
  kernel: [
    2,
    2
  ],
  stride: [
    2,
    2
  ],
  padding: "Valid"
}, [[
    1,
    224,
    224,
    64
  ]]);

testCodegen("AvgPool2D", {
  TAG: "AvgPool2D",
  kernel: [
    2,
    2
  ],
  stride: [
    2,
    2
  ],
  padding: "Valid",
  countIncludePad: false
}, [[
    1,
    112,
    112,
    128
  ]]);

testCodegen("BatchNorm", {
  TAG: "BatchNorm",
  epsilon: 1e-5,
  momentum: 0.1
}, [[
    1,
    56,
    56,
    256
  ]]);

testCodegen("Conv1D", {
  TAG: "Conv1D",
  filters: 64,
  kernel: 3,
  stride: 1,
  padding: "Same",
  dilation: 1,
  groups: 1
}, [[
    4,
    128,
    32
  ]]);

testCodegen("GlobalMaxPool", "GlobalMaxPool", [[
    1,
    7,
    7,
    512
  ]]);

testCodegen("GlobalAvgPool", "GlobalAvgPool", [[
    1,
    7,
    7,
    512
  ]]);

testCodegen("LayerNorm", {
  TAG: "LayerNorm",
  axes: [-1],
  epsilon: 1e-5
}, [[
    4,
    128,
    256
  ]]);

testCodegen("Attention", {
  TAG: "ScaledDotProductAttention",
  dropout: 0.0,
  causal: false
}, [[
    2,
    64,
    128
  ]]);

testCodegen("Embedding", {
  TAG: "Embedding",
  numEmbeddings: 50000,
  embeddingDim: 512
}, [[
    4,
    128
  ]]);

testCodegen("Clip", {
  TAG: "Clip",
  min: 0.0,
  max: 6.0
}, [[
    4,
    256
  ]]);

console.log("\n=== Done ===");

export {
  log,
  printShape,
  testInfer,
  testCodegen,
}
/*  Not a pure module */
